"""
PyTorch Dataset and DataLoader for pixel coordinate regression.
Loads the .npz files generated by dataset_gen.py.
"""

import os
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
from torchvision.utils import make_grid


class PixelDataset(Dataset):
    """
    Loads:
        images: (N, 50, 50) uint8
        labels: (N, 2) float32 normalized [0,1]
    Returns:
        image tensor: (1, 50, 50), float32 in [0,1]
        label tensor: (2,), float32 in [0,1]
    """
    def __init__(self, npz_path: str):
        if not os.path.exists(npz_path):
            raise FileNotFoundError(f"{npz_path} not found.")

        data = np.load(npz_path)
        self.images = data["images"]
        self.labels = data["labels"].astype(np.float32)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img = self.images[idx].astype(np.float32) / 255.0  # normalize grayscale
        img = torch.tensor(img).unsqueeze(0)  # (1,50,50)

        label = torch.tensor(self.labels[idx], dtype=torch.float32)
        return img, label


def get_dataloaders(batch_size=64, num_workers=0):
    train_set = PixelDataset("data/train.npz")
    val_set = PixelDataset("data/val.npz")
    test_set = PixelDataset("data/test.npz")

    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True,
                              num_workers=num_workers)
    val_loader = DataLoader(val_set, batch_size=batch_size, shuffle=False,
                            num_workers=num_workers)
    test_loader = DataLoader(test_set, batch_size=batch_size, shuffle=False,
                             num_workers=num_workers)
    return train_loader, val_loader, test_loader


def visualize_batch(images, labels, n=16):
    """Visualize a grid of 16 images with red dots at their true coordinates."""
    images = images[:n]
    labels = labels[:n]

    grid = make_grid(images, nrow=4, normalize=True)
    np_img = grid.numpy().transpose(1, 2, 0)

    plt.figure(figsize=(6, 6))
    plt.imshow(np_img[:, :, 0], cmap="gray")

    # Overlay true (x,y) positions
    for i in range(n):
        x = labels[i][0].item() * 49
        y = labels[i][1].item() * 49

        row = i // 4
        col = i % 4
        # Each image is 50px wide in the grid
        grid_x = col * 50 + x
        grid_y = row * 50 + y

        plt.scatter([grid_x], [grid_y], c="red", s=20)

    plt.axis("off")
    plt.show()


if __name__ == "__main__":
    train_loader, val_loader, test_loader = get_dataloaders()

    print("Train batches:", len(train_loader))
    imgs, labs = next(iter(train_loader))
    print("Batch shape:", imgs.shape, labs.shape)

    visualize_batch(imgs, labs)
